### ISSUE TITLE
Create DOI on subsets of data

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/ckanext-nhm#112]
So in the same way staff can create subsets of data, so someone downloading data can choose to create it as a dataset and get a DOI. "Do you want to create a persistent copy of this data".

Preserve the query string.

Copy data into another dataset.

Collections dataset.

**Comment by benscott** [comment]
Will be added to RDA proposal

**Comment by alycejenni** [comment]
Done: https://github.com/NaturalHistoryMuseum/ckanext-query-dois
