### ISSUE TITLE
'Follow dataset' button doesn't prompt for user login

### ISSUE THREAD

**Issue by rossmounce** [NaturalHistoryMuseum/ckanext-nhm#218]
Scenario: New users will come to the site without a login.
They will browse dataset, think, "hey cool", click the 'Follow' button.

**Nothing Happens**

You need to prompt users to register/login if they click the 'Follow' button (when not logged in).
Perhaps even state below the button that this is a feature for registered users-only.

![2015-05-06-115146_1366x744_scrot](https://cloud.githubusercontent.com/assets/824120/7491908/6a545fe4-f3e6-11e4-9879-33cd3d5c4c3c.png)

**Comment by benscott** [comment]
Removed follow button - this has been replace with twitter updates.
