### ISSUE TITLE
Unicode Character U+0085 (Next Line) in 70 records in specimen collection dataset

### ISSUE THREAD

**Issue by rossmounce** [NaturalHistoryMuseum/ckanext-nhm#229]
csvclean found some errors in that new collections data export file btw: there are line-break characters or something (U+0085) in 70 different records, which it doesn't like: https://gist.github.com/rossmounce/66ab21bb79b04aa640bc

**Comment by alycejenni** [comment]
Can't find the offending fields in the current data, so hopefully this has been fixed
