### ISSUE TITLE
Disappearing images (non-persistent)

### ISSUE THREAD

**Issue by rossmounce** [NaturalHistoryMuseum/ckanext-nhm#246]
Back on May 19th when I wrote a blog post: http://rossmounce.co.uk/2015/05/19/text-mining-for-museum-specimen-identifiers/

There was an image available and associated with "86.10.4.2" (a _Caiman_) on the data portal. 
I've just noticed there is now no such link to any image from that specimen page:
http://data.nhm.ac.uk/specimen/8559613e-f2a3-447c-aa1a-d476600d3293

The image was available at this URL (but is available no longer): http://www.nhm.ac.uk/emu-classes/class.EMuMedia.php?irn=158767&amp;image=yes&amp;width=750&amp;height=500

**Comment by benscott** [comment]
Sorry about that, the Museum's been migrating to a new image server.  It's now online, and our specimen images are now available again.  I'm afraid the URLs have changed (we don't have control over the URLs & there are no redirects) - the new URL for the image in your blog would be:

http://www.nhm.ac.uk/services/media-store/asset/dcd637df6533f359ff570c89afa5669085ba0d71/contents/preview
