### ISSUE TITLE
Populate higher taxonomy using info from other fields

### ISSUE THREAD

**Issue by rossmounce** [NaturalHistoryMuseum/ckanext-nhm#261]
I've noticed there are some relatively 'cheap' data improvements that can be made to the data records.

e.g. this [specimen record](http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/1507665) of _Natalina_ clearly has this information "Sub department: Mollusca" in it but not much else.	 

yet if I search for [_Natalina_ + Phylum:Mollusca](http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb?q=natalina&view_id=6b611d29-1dcf-4c60-b6b5-4cbb69fdf4fe&filters=_f%3AscientificName%7C_f%3AscientificNameAuthorship%7C_f%3Aphylum%7C_f%3Aclass%7C_f%3Afamily%7C_f%3Agenus%7C_f%3AspecificEpithet%7C_f%3AinfraspecificEpithet%7C_f%3Alocality%7C_f%3AviceCountry%7C_f%3Acountry%7C_f%3ArecordedBy%7C_f%3AtypeStatus%7C_f%3AcatalogNumber%7C_f%3AcollectionCode%7Cphylum%3AMollusca) The above record is not returned. In fact the search returns just 8 records.

Whereas a search for just _Natalina_ returns [62 records](http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb?view_id=6b611d29-1dcf-4c60-b6b5-4cbb69fdf4fe&q=natalina&filters=_f%3AscientificName%7C_f%3AscientificNameAuthorship%7C_f%3Aphylum%7C_f%3Aclass%7C_f%3Afamily%7C_f%3Agenus%7C_f%3AspecificEpithet%7C_f%3AinfraspecificEpithet%7C_f%3Alocality%7C_f%3AviceCountry%7C_f%3Acountry%7C_f%3ArecordedBy%7C_f%3AtypeStatus%7C_f%3AcatalogNumber%7C_f%3AcollectionCode). All those 62 Natalina records should be returned in a search for Natalina AND Phylum:Mollusca.

This makes me extremely nervous about using any of the higher taxonomy filters. Seems like a lot of this information isn't there, but could reasonably be inferred from other information.

**Comment by benscott** [comment]
It's a very good point, and would be easy to fix.  Unfortunately a principle of the portal is it shouldn't modify or improve data from our collections dataset.  This has been passed to our data managers to implement in our CMD.
