### ISSUE TITLE
Truncated fields

### ISSUE THREAD

**Issue by llivermore** [NaturalHistoryMuseum/ckanext-nhm#263]
Some fields are truncated, for example, the recorded by field.

"Hillery B. Warner; Natural History Museum; Department of Entomology; b.18/12/1984; Warner; Mr Lauren"

http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/2833153

**Comment by benscott** [comment]
With SOLR dataset no fields are truncated.
