### ISSUE TITLE
Remove inconsistent italics on scientific names

### ISSUE THREAD

**Issue by llivermore** [NaturalHistoryMuseum/ckanext-nhm#266]
The name fields are used inconsistently across departments and the inconsistent italics formatting looks bad. 

Note that the neither Canadensys or GBIF italicise names:
http://data.canadensys.net/explorer/en/resources/cmmf-specimens/occurrences/8248
http://www.gbif.org/species/1759736
http://www.gbif.org/species/1759736/classification

**Comment by alycejenni** [comment]
As far as I know, it's standard practice to italicise the genus and species (/sub) in botany and zoology, and since this issue was opened, GBIF have started italicising their names.
I'm going to try standardising the italics (with collection-dependent rules) rather than removing them entirely.
