### ISSUE TITLE
Resource file type not updating in the dataset list

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#273]
Icon/label doesn't update in the dataset list when the resource's file type is changed, or re-uploaded in a different format.

**Comment by alycejenni** [comment]
@mswoodburn is this with all filetypes? I can't recreate it with csv <-> tsv.

**Comment by mswoodburn** [comment]
@alycejenni Can't recreate this either now - was raised two years ago, so looks some update since then has fixed it.

**Comment by alycejenni** [comment]
mysterious fixes are my favourite :)
