### ISSUE TITLE
Issues adding resources to datastore

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#275]
Added a private dataset (http://data.nhm.ac.uk/dataset/test-embargo-summary), and uploaded three resources, an xlsx file and two csvs, with the same content (14 columns, header row + 2 content rows.  Attempted to create views by uploading to datastore, but the result is endless loading when viewing the xlsx (may not have picked up the headers), and server error for the csvs.

**Comment by benscott** [comment]
There is an issue with private datasets and parsing data files.  This is an issue with CKAN itself: the parsing uses the API. Private datasets aren't available through the API, and therefore cannot be parsed.  Need to investigate patching CKAN to fix this.

**Comment by alycejenni** [comment]
Fixed with new backend
