### ISSUE TITLE
ORCIDs

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/ckanext-nhm#282]
http://members.orcid.org/api/introduction-orcid-member-api

Need to be a member. And then when you create a dataset, write to ORCIDs service to associate dataset with a user.

Optional ORCID. Linked to LDAP.

**Comment by alycejenni** [comment]
See [ckanext-orcid-datasets](https://github.com/NaturalHistoryMuseum/ckanext-orcid-datasets)
