### ISSUE TITLE
Botany identification

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/ckanext-nhm#285]
For Botany, current "Identified by" is wrong - identification fields are for the Scientific Name, and full identification history should be used. e.g. http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/5055973

Need to:
1. Clearly show the identification fields (Identified by, Date identified & Type status) are for the Scientific Name (requires redesign - move fields into classification section?) 
2. "Type status" field is incorrect - need to just use type status for the current Scientific Name. Data mapping seems to be using type status for any of the determinations.
3. "Collection date" field is incorrect - make sure it uses the correct KE EMu DwC field (which is for the Scientific name)
4. Have full determinations history table, with the fields: 
   - Taxon name
   - Filed as (should be yes/no - not true false)
   - Type of type
   - Identified by
   - Date identified

Reported by JW - to check before live.

**Comment by benscott** [comment]
Never heard back from JW about this, and this approach isn't correct for all groups.  Postponed until I get more info.

**Comment by jrdh** [comment]
I wonder if this has any relation to this more recent report of issues with Botany taxonomies: https://github.com/NaturalHistoryMuseum/data-importer2/issues/17?
