### ISSUE TITLE
Allow all authors to be displayed

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/ckanext-nhm#293]
The portal truncates long author lists with ‘et al' (e.g., http://data.nhm.ac.uk/dataset/predicts-site-level-summary-biodiversity-and-pressure-data), with no way to view the complete author list.

Could the portal be altered to show the first N authors and the last author, with a clickable ellipsis to toggle middle authors? This is the scheme used by Scientific Data e.g., http://www.nature.com/articles/sdata201617 The last author tends to be the Principal Investigator on a project, so it is good to always show them.

**Comment by benscott** [comment]
Remove et al displaying in header.
