### ISSUE TITLE
Disable download button for private datasets (was: "Downloads of newly added data are broken")

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/ckanext-nhm#296]
- create a new dataset on the portal
- create and upload a file `test.csv` that contains a couple of rows and columns (exact contents are unimportant)
- download the file - you will be emailed a link
- click the link you receive, something like `http://data.nhm.ac.uk/resources/f231b2b0de35d96613772e3c564fdd9c-97-1464687712.zip`

The file within the downloaded zip is an html document (e.g., [downloaded_file.txt](https://github.com/NaturalHistoryMuseum/ckanext-nhm/files/290784/downloaded_file.txt)) that prompts for a username and password.

**Comment by benscott** [comment]
This is just for private datasets - the html document is an access denied page.  Need to improve the UI for private datasets, disable the download & API buttons to make it clear the data is unavailable.
