### ISSUE TITLE
Stats not updating

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#297]
The stats page hasn't been updating since November 2015: [(http://data.nhm.ac.uk/about/statistics/records)]

Current text on page: "Record statistics are updated daily - these figures were last updated on November 25, 2015"

**Comment by benscott** [comment]
There is a command for updating the stats in ckanext-nhm:

     paster datastore update-stats -c [path to development.ini].  

This should have been running via cron, but hasn't been. I have just re-run the command so stats are now correct and added it to cron so they will update weekly.
