### ISSUE TITLE
GBIF issue dropdown in filter doesn't return a list

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#300]
Perpetual searching

**Comment by mswoodburn** [comment]
Also an issue for the Vice Country field.  Prevents users from filtering on these fields.

**Comment by benscott** [comment]
GBIF Issues are now facets & working correctly.

Vice Country field is no longer included - raised as separate data import issue: https://github.com/NaturalHistoryMuseum/data-importer/issues/20
