### ISSUE TITLE
Maps not working

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/ckanext-nhm#301]
MapQuest have discontinued direct tile access, which breaks our maps

![image](https://cloud.githubusercontent.com/assets/1640027/16843303/9552e8de-49d8-11e6-8da3-0ca6dc99765c.png)

We need to sign up to 'MapQuest plugin for Leaflet': http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by atrawog** [comment]
Another possibility would be to use another freely available tile source like Stamen or Mapzen https://mapzen.com/blog/closing-mapquest-open

**Comment by benscott** [comment]
Moved to Mapbox tiles
