### ISSUE TITLE
Big file manual upload not working

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#302]
Following the instructions in https://docs.google.com/document/d/117ejP1Qlh-lE2WTxT3Bc9q-valrGuaeP0yWzpP2bh_w/edit#heading=h.dkg3dc5ws8a2 in order to upload a ~600Mb zip file

Resource: http://data.nhm.ac.uk/dataset/cicadas-of-india/resource/bcb46c6b-8580-4f21-bbb2-3468d26ac00a

The datastore file replacement seems to have worked (having checked the appropriate folder in /var/lib/ckan/default/resources/), but the download link from the Portal still provides the original dummy file.  This was several weeks ago now, so doesn't appear to be a time-limited caching issue.

**Comment by alycejenni** [comment]
Given that this was almost 6 years ago, I'm going to assume this got sorted
