### ISSUE TITLE
Vice Country doesn't display (and needs renaming)

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#310]
Vice Country is always set to SHOW under 'Configure fields and filters', and reverts to SHOW if set to HIDE, but the column is never visible on the datagrid.  Judging by the field use, it should also be renamed 'Vice County'.

**Comment by alycejenni** [comment]
This was probably because the data importer field had been renamed to viceCounty, but the front end wasn't changed to reflect that.
