### ISSUE TITLE
Add Altmetric-friendly meta tags

### ISSUE THREAD

**Issue by essvee** [NaturalHistoryMuseum/ckanext-nhm#337]
Please could you add the meta tags below to each dataset to enable altmetric tracking?

- citation_doi
- citation_author
- citation_title
- citation_online_date

eg for the collection specimens set:

	<meta name="citation_doi" content="doi:10.5519/0002965" />
	<meta name="citation_author" content="Natural History Museum" />
	<meta name="citation_title" content="Collection specimens" />
	<meta name="citation_online_date" content="2014-12-08" />

More detail at: https://help.altmetric.com/support/solutions/articles/6000141419-what-metadata-is-required-to-track-our-content-

**Comment by essvee** [comment]
<meta name="citation_publisher" content="Natural History Museum" />

... probably could've guessed that ;)

**Comment by benscott** [comment]
Altmetric meta tags added- view-source:http://data.nhm.ac.uk/dataset/collection-specimens
