### ISSUE TITLE
Prefer https to http in DOI links

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/ckanext-nhm#341]
The 'Cite as' section of the dataset page uses `http` to link to the DOI resolver, e.g. https://data.nhm.ac.uk/dataset/predicts-site-level-summary-biodiversity-and-pressure-data links to http://dx.doi.org/10.5519/0018993. The link to `dx.doi.org` should use `https`.

**Comment by rossmounce** [comment]
One could go further with this and change the `dx.doi.org` to just `doi.org` whilst you're at it:

https://www.crossref.org/blog/new-crossref-doi-display-guidelines-are-on-the-way/
