### ISSUE TITLE
Temporarily redact recordedBy and identifiedBy fields

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#342]
These fields need to be blanked in short term due to DOB issues.  The longer term fix should be for Axiell to update their DwC update scripts.

**Comment by benscott** [comment]
Currently redacted.  @mswoodburn - can you confirm with Axiell where we are with the fix please.

**Comment by mswoodburn** [comment]
Now unredacted by Josh, incorrect fix done by Axiell which removes all dates, but safe to publish again at least.

**Comment by mswoodburn** [comment]
Closed
