### ISSUE TITLE
Rendering of points on map extremely slow

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#347]
Both initial rendering, and refreshing when zooming and moving

**Comment by mswoodburn** [comment]
Also doesn't display any points at all for the complete unfiltered dataset

**Comment by benscott** [comment]
Cache issue, now fixed. You'll probably need to clear browser data cache (or wait a few hours).

That will also have been affecting the speed, so it's faster now.  I'll keep an eye on it and possibly up the server resources if it's still too slow.
