### ISSUE TITLE
Error when using advanced filter with an option which is an array

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#355]
E.g. filtering on project for ["eMesozoic","Airless"]: 

http://data.nhm.ac.uk/dataset/56e711e6-c847-4f99-915a-6894bb5c5dea/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb?view_id=203a0ae5-6a14-480a-a407-27eeb9373858&filters=project%3A%5B%22eMesozoic%22%2C+%22Airless%22%5D

**Comment by benscott** [comment]
Fixed in datasolr - https://github.com/NaturalHistoryMuseum/ckanext-datasolr/pull/10
