### ISSUE TITLE
Encoding issues in csv downloads

### ISSUE THREAD

**Issue by mswoodburn** [NaturalHistoryMuseum/ckanext-nhm#391]
There are a lot of character encoding issues in the portal downloads, names in particular affected e.g. IbÃ¡nez for Ibánez, BÃ¶ÃŸneck for Bößneck.  They look fine in Solr, so related to the csv writer?

**Comment by jrdh** [comment]
I can see issues but only in the `dynamicProperties` column of the DwC `occurrence.csv` download, is that correct? I've got a fix for that lined up which I'll push, but it would be good to confirm this is the only issue and there aren't any other problems in other columns.
