### ISSUE TITLE
GBIF Images missing

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/ckanext-nhm#398]
Images aren't going through to GBIF:

https://www.gbif.org/occurrence/gallery?publishing_org=19456090-b49a-11d8-abeb-b8a03c50a862

**Comment by jrdh** [comment]
Interesting. I wonder if this is related to the issues here https://github.com/NaturalHistoryMuseum/data-portal/issues/210 and then https://github.com/gbif/portal-feedback/issues/1358. Once we get a successful ingestion complete on GBIF we'll know.

**Comment by jrdh** [comment]
I'll keep this open until the changes have been deployed and then confirmed on GBIF.

**Comment by jrdh** [comment]
This has been solved now.
