### ISSUE TITLE
Link of alternative resources (RDF, Turtle etc.) not resolving to a data file

### ISSUE THREAD

**Issue by infinite-dao** [NaturalHistoryMuseum/ckanext-nhm#455]
Hej-hej,

**Description**
 If I view http://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724 I get redirected to https://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/4993567 and in that view the resource links are decoded in a ?mistaken/wrong way:
```
<link rel="alternate" type="text/n3" href="https://data.nhm.ac.ukobject.rdf?_format=n3&amp;uuid=8846cc56-b2f3-4e0a-9a43-6c75dfd27724">
<link rel="alternate" type="text/ttl" href="https://data.nhm.ac.ukobject.rdf?_format=ttl&amp;uuid=8846cc56-b2f3-4e0a-9a43-6c75dfd27724">
<link rel="alternate" type="application/rdf+xml" href="https://data.nhm.ac.ukobject.rdf?_format=xml&amp;uuid=8846cc56-b2f3-4e0a-9a43-6c75dfd27724">
<link rel="alternate" type="application/rdf+xml" href="https://data.nhm.ac.ukobject.rdf?_format=rdf&amp;uuid=8846cc56-b2f3-4e0a-9a43-6c75dfd27724">
```
It does not find the resources. It seems located in  https://github.com/NaturalHistoryMuseum/ckanext-nhm/blob/e1ef81b88afb650bcdd70341541366fafe0a7603/ckanext/nhm/theme/templates/record/specimen.html#L5

**Expected Behaviour**
Resolve to a data source of type `text/n3` `text/ttl` `application/rdf+xml` and get the data ;-)

**To Reproduce**

1. open http://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724
2. try to get the `<link rel="alternate" …>` resources of it, e.g. https://data.nhm.ac.ukobject.rdf?_format=rdf&uuid=8846cc56-b2f3-4e0a-9a43-6c75dfd27724

I hop it can be fixed, to get also RDF
Kind regards

**Comment by jrdh** [comment]
Hey @infinite-dao, thanks for the heads up, I'll go fix this right away!

**Comment by jrdh** [comment]
All sorted! Thanks again for the heads up.

**Comment by infinite-dao** [comment]
Great that the RDF is now available!

When I request:
```
wget --header='Accept: application/rdf+xml'  --header='Content: application/rdf+xml'   "http://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724"
```
I now get a HTTP response code of 500 (internal server error). Should the `wget` request resolve also to the RDF resource, which in this case is http://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724.rdf ?

**Comment by jrdh** [comment]
Yep that's another bug - fixed it here: https://github.com/NaturalHistoryMuseum/ckanext-nhm/commit/0ac638af334d39efffd7f38514eeb4fc5df0b3f5 should be working now.

**Comment by infinite-dao** [comment]
OK, fine, now it works great. Thank you.
