### ISSUE TITLE
No 'download' option for MetCat dataset

### ISSUE THREAD

**Issue by essvee** [NaturalHistoryMuseum/ckanext-nhm#539]
The MetCat resource in the [MetCat 2 dataset](https://data-nlb-stg-01.nhm.ac.uk/dataset/metcat-2) on staging doesn't give you the option to download the full dataset, just a 'go to resource' link, which doesn't resolve correctly. The resource is populated through the API and loaded in as JSON. Ideally, you'd be able to download the full dataset in a flat file in the format of your choice, as per usual.

**Comment by jrdh** [comment]
This is now fixed on staging and will be released on live next week!
