### ISSUE TITLE
Image 404 in footer

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/ckanext-nhm#547]
Not sure why but:

![image](https://user-images.githubusercontent.com/4718259/168883841-e3e52e57-8eb4-4382-9fd4-74d28999fabb.png)

This is obviously extremely low priority.

**Comment by alycejenni** [comment]
This was because `ckan.site_logo` was set to `/uploads/admin/logo.png` in the `system_info` table, so that overrode the config option at runtime. Fixed now.

**Comment by jrdh** [comment]
Dang, my only guess can be that I did this accidentally when modifying the status that now lives in the same live config? I'll be more careful next time!
