### ISSUE TITLE
Display physical location of specimen

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/ckanext-nhm#96]
It would be useful to display the physical location of the specimen - e.g. drawer/cabinet/collection area.  This should only be revealed to Museum staff, so rather than bring in the data from the KE EMu import, it's probably best to use the EMu API to display the info on record view. 

This information should only be presented to Museum staff so must be restricted to authorised users / internal IP range. Best to display a message "login to view location" restricted to internal IP range, and then display info for authenticated users only.

**Comment by benscott** [comment]
Is this even possible now the Emu API has been turned off?

**Comment by alycejenni** [comment]
NaturalHistoryMuseum/dataportal-docs#20
